project:
  type: book
  output-dir: _book
  
book:
  title: "Surviving Data Science"
  author: "James Joseph Balamuta"
  description: | 
    TBA
  #cover-image: images/cover.png
  site-url: https://textbooks.thecoatlessprofessor.com/sds
  repo-url: https://github.com/coatless-textbooks/sds
  repo-branch: main
  repo-actions: [edit]
  sharing: [twitter, facebook, linkedin]
  chapters:
    - index.qmd
    - part: my-first-book.qmd
      chapters: 
        - hello-world.qmd
  appendices:
    - appendix-notes.qmd
    
format:
  html: 
    theme: cosmo
    code-link: true
